const CSV_DATA =
`Name,Gender,Branch,Room Number,Car Number,D1T,D2T,Outing Number,Separate Event Number
ALDRINNE M. ARRO,M,ALABANG,,,Track 3 : Personal Management,Track 2 : Bible Study,,
ANGELO V. DEGORIO,M,ALABANG,,,Track 2 : Participating in worship,Track 1 : Leading worship,,
LEMUEL GAVIN SARET,M,ALABANG,,,Track 1 : How to run a ministry,Track 2 : Bible Study,,
JON RAY BIEN D. LOGICA,M,ALABANG,,,Track 4 : How to make our branches attractive to younger generation,Track 2 : Bible Study,,
JOHN ADRIAN A. CIELOS,M,ALABANG,,,Track 4 : How to make our branches attractive to younger generation,Track 2 : Bible Study,,
PAMELA ANN M. DUQUE,F,ALABANG,,,Track 3 : Personal Management,Track 2 : Bible Study,,
RICHMOND M. BANZUELO,M,ALABANG,,,Track 2 : Participating in worship,Track 3 : Rekindling Commitment,,
ANJIL S. AUSTRIA,M,ALABANG,,,Track 3 : Personal Management,Track 4 : How to reach out effectively to Gen Zs,,
CHRISTIAN VANESSA OLEA AUSTRIA,F,ALABANG,,,Track 3 : Personal Management,Track 2 : Bible Study,,
OLEEN JOYCE B FLORENDO,F,ALABANG,,,Track 2 : Participating in worship,Track 3 : Rekindling Commitment,,
JOBELLE S. GALLO,F,ALABANG,,,Track 4 : How to make our branches attractive to younger generation,Track 4 : How to reach out effectively to Gen Zs,,
RIZA L. BERSABAL,F,ALABANG,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
JAKE D. DELA CRUZ,M,ALABANG,,,Track 4 : How to make our branches attractive to younger generation,Track 4 : How to reach out effectively to Gen Zs,,
MIKHAELLA L RACELIS,F,ALABANG,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
IRA JAMAICA T. LACO,F,ALABANG,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
JAN AUDI BLEZ M. NAVARRO,M,ALABANG,,,Track 2 : Participating in worship,Track 1 : Leading worship,,
MARC RAZEL B. BUENAFE,M,ALABANG,,,Track 1 : How to run a ministry,Track 3 : Rekindling Commitment,,
DYVE D CANDAZA,M,ALABANG,,,Track 3 : Personal Management,Track 4 : How to reach out effectively to Gen Zs,,
JOANNA MARIE I QUINTOS,F,ALABANG,,,Track 3 : Personal Management,Track 4 : How to reach out effectively to Gen Zs,,
JON SAMUEL S MENDEZ,M,ALABANG,,,Track 4 : How to make our branches attractive to younger generation,Track 3 : Rekindling Commitment,,
IÑIGO MIGUEL G. VILLANUEVA,M,ALABANG,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
MAUI ARCA,M,ALABANG,,,Track 2 : Participating in worship,Track 3 : Rekindling Commitment,,
CAMILLE R. GARCIA,F,ALABANG,,,Track 2 : Participating in worship,Track 3 : Rekindling Commitment,,
AMIEL M. MALONZO,M,ANGELES,,,Track 4 : How to make our branches attractive to younger generation,Track 4 : How to reach out effectively to Gen Zs,,
ALDWYN JOHN T BAUTISTA,M,ANGELES,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
AIRAM MIGUEL M. DIZON,M,ANGELES,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
ALLAINE CASTRO GALANG,F,ANGELES,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
JIANE RHANE A. REGALA,F,ANGELES,,,Track 4 : How to make our branches attractive to younger generation,Track 4 : How to reach out effectively to Gen Zs,,
KIMBERLY Q. DELA CRUZ,F,ANGELES,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
MICHAELA ANTONETTE M. PANTIG,F,ANGELES,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
NIKI G. INARDA,F,ANGELES,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
JOSE LORENZO M. CUNANAN,M,ANGELES,,,Track 4 : How to make our branches attractive to younger generation,Track 4 : How to reach out effectively to Gen Zs,,
KATHY ROSE T. SANTOS,F,ANGELES,,,Track 4 : How to make our branches attractive to younger generation,Track 4 : How to reach out effectively to Gen Zs,,
JAN MARVIN P. DELA CRUZ,M,ANGELES,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
KIMBERLY F. POLICARPIO,F,ANGELES,,,Track 2 : Participating in worship,Track 3 : Rekindling Commitment,,
JILLIAN MAE D. GUIAO,F,ANGELES,,,Track 3 : Personal Management,Track 2 : Bible Study,,
JELLY B AGUSTIN,F,ANGELES,,,Track 2 : Participating in worship,Track 4 : How to reach out effectively to Gen Zs,,
ISMINE JOICE S. HIPOLITO,F,ANGELES,,,Track 3 : Personal Management,Track 4 : How to reach out effectively to Gen Zs,,
MARK SPENCER R. MALIG,M,ANGELES,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
JUN EXEQUIEL E. SAYLON,M,ANGELES,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
KRISHIA JANINE P. GUBATON,F,ANGELES,,,Track 4 : How to make our branches attractive to younger generation,Track 3 : Rekindling Commitment,,
GLENINE ANNE P PANGILINAN,F,ANGELES,,,Track 3 : Personal Management,Track 2 : Bible Study,,
MARVIN SANTOS MACAPINLAC,M,ANGELES,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
JAIME JUROE S BONITO,M,ANGELES,,,Track 1 : How to run a ministry,Track 3 : Rekindling Commitment,,
JOVINIA S LUCAS,F,BAGUIO,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
ELLISON DALE M. RAGUDO,M,BAGUIO,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
CATHERINE ROSE D. SACANLE,F,BAGUIO,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
RICHARD DEAN F. BASA,M,BAGUIO,,,Track 3 : Personal Management,Track 4 : How to reach out effectively to Gen Zs,,
RICHARD M. BUHAYO,M,BAGUIO,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
RENZ IVERSON B. MACAGBA,M,BAGUIO,,,Track 1 : How to run a ministry,Track 3 : Rekindling Commitment,,
GELLAINE A. SALVACION,F,BATANGAS,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
ERICA MAE I. MERCADO,F,BATANGAS,,,Track 2 : Participating in worship,Track 1 : Leading worship,,
CHRISHA MAE S. REMORERAS,F,BATANGAS,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
DENISE JAMES C CHUA,F,BATANGAS,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
JUDY ANNE J PEÑA,F,BATANGAS,,,Track 1 : How to run a ministry,Track 3 : Rekindling Commitment,,
MARY ANTONETTE B. MIRANDA,F,BATANGAS,,,Track 3 : Personal Management,Track 4 : How to reach out effectively to Gen Zs,,
MARY LOURDES D. BORBON,F,BATANGAS,,,Track 4 : How to make our branches attractive to younger generation,Track 2 : Bible Study,,
KATHERINE MENDEZ,F,BATANGAS,,,Track 1 : How to run a ministry,Track 3 : Rekindling Commitment,,
ANGEL S. DEL ROSARIO,M,BATANGAS,,,Track 2 : Participating in worship,Track 4 : How to reach out effectively to Gen Zs,,
LYZETTE A. LAZARTE,F,BATANGAS,,,Track 3 : Personal Management,Track 2 : Bible Study,,
IVY MELISSA M. BALUYOT,F,BGC,,,Track 4 : How to make our branches attractive to younger generation,Track 2 : Bible Study,,
SAMANTHA B. MARWELES,F,BGC,,,Track 2 : Participating in worship,Track 1 : Leading worship,,
ARNEL BIEN H. FRANCISCO,M,BGC,,,Track 1 : How to run a ministry,Track 3 : Rekindling Commitment,,
RINO C. BALUYOT JR.,M,BGC,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
ARIANNE NINA M. AREVALO,F,BGC,,,Track 4 : How to make our branches attractive to younger generation,Track 3 : Rekindling Commitment,,
MICHELLE ANGELICA C. ARRANZ,F,BGC,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
RHOMEL ISAAC B. MARCOJOS,M,BGC,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
PRECILYN B. CASPILLO,F,BGC,,,Track 2 : Participating in worship,Track 4 : How to reach out effectively to Gen Zs,,
IRINE T. SALES,F,BGC,,,Track 3 : Personal Management,Track 1 : Leading worship,,
MERIE JUDAINE D. CARINGAL,F,BGC,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
MARICAR D. AUDITOR,F,BGC,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
HERBERT JOSEPH ROXAS ESLING,M,BGC,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
JUSTIN ANTHONY B. BUENAFE,M,BGC,,,Track 3 : Personal Management,Track 2 : Bible Study,,
KRISTALYNNE B. GREGANDA,F,CABUYAO,,,Track 3 : Personal Management,Track 1 : Leading worship,,
NICOLE JOYCE V TUPAS,F,CABUYAO,,,Track 2 : Participating in worship,Track 4 : How to reach out effectively to Gen Zs,,
JUAN FRANCO B DE GUZMAN,M,CABUYAO,,,Track 4 : How to make our branches attractive to younger generation,Track 3 : Rekindling Commitment,,
MARK DAVID T. DOMINO,M,CABUYAO,,,Track 1 : How to run a ministry,Track 2 : Bible Study,,
FRANCISCO EZEKIEL M. ESPINOSA,M,CAVITE,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
CHRISTINE JOY M. ROMILLA,F,CAVITE,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
CHRISTIAN M DELA GRACIA,M,CAVITE,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
AYN CYRIL TIANGCO,M,CAVITE,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
MARK ANGEL V. REYES,M,CAVITE,,,Track 3 : Personal Management,Track 4 : How to reach out effectively to Gen Zs,,
KIM PAULO SIERRA,M,CAVITE,,,Track 4 : How to make our branches attractive to younger generation,Track 2 : Bible Study,,
VEENUZ MARGARETTE C. DEL ROSARIO,F,CAVITE,,,Track 1 : How to run a ministry,Track 2 : Bible Study,,
KATERINE GAIL CATACUTAN PANGILINAN,F,CAVITE,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
RINA MARIE A. VERANO,F,CAVITE,,,Track 4 : How to make our branches attractive to younger generation,Track 3 : Rekindling Commitment,,
ROWELL IAN S. SALVADOR,M,CAVITE,,,Track 2 : Participating in worship,Track 4 : How to reach out effectively to Gen Zs,,
SEAN VINCENT L. CABEZAS,M,CAVITE,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
AILEEN MAY B. TOLENTINO,F,CAVITE,,,Track 2 : Participating in worship,Track 4 : How to reach out effectively to Gen Zs,,
ROLLAINE JOVEL JAMLIG PADDRES,F,CAVITE,,,Track 4 : How to make our branches attractive to younger generation,Track 4 : How to reach out effectively to Gen Zs,,
PRINCESS ANN L. PAGBILAO,F,CAVITE,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
ALAIZA T. ENCARNACION,F,CAVITE,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
REMEDIOS BEATRICE N. GAON,F,CAVITE,,,Track 1 : How to run a ministry,Track 2 : Bible Study,,
DEO J. JOLLOSO,M,CAVITE,,,Track 2 : Participating in worship,Track 4 : How to reach out effectively to Gen Zs,,
MARK JASON UMAS-AS CASIL,M,CAVITE,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
JUVY GRACE B. ADRIAS,F,CAVITE,,,Track 2 : Participating in worship,Track 3 : Rekindling Commitment,,
FRANCES MARGARET D CHUAHIONG,F,CAVITE,,,Track 3 : Personal Management,Track 2 : Bible Study,,
MARY CARELL D. SABA,F,CAVITE,,,Track 1 : How to run a ministry,Track 3 : Rekindling Commitment,,
JAYCEL C. CAPUNONG,F,CAVITE,,,Track 3 : Personal Management,Track 1 : Leading worship,,
HENSON B. GLODO,M,CENTRAL,,,Track 4 : How to make our branches attractive to younger generation,Track 2 : Bible Study,,
JAMINO F. GONZALES,M,CENTRAL,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
RHOMEL IGNATIUS B. MARCOJOS,M,CENTRAL,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
CHARISSE N. SANCHEZ,F,CENTRAL,,,Track 1 : How to run a ministry,Track 3 : Rekindling Commitment,,
CARLOS V. PALATTAO,M,CENTRAL,,,Track 4 : How to make our branches attractive to younger generation,Track 3 : Rekindling Commitment,,
SHAINA R DUCUT,F,CENTRAL,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
MANLEY M. SALAZAR JR.,M,CENTRAL,,,Track 3 : Personal Management,Track 1 : Leading worship,,
JOSHUA MIKHAEL O. BONDOC,M,CENTRAL,,,Track 2 : Participating in worship,Track 1 : Leading worship,,
"JONINA RAE, DARLUCIO, VILVESTRE",F,CENTRAL,,,Track 4 : How to make our branches attractive to younger generation,Track 4 : How to reach out effectively to Gen Zs,,
ARLENE WARKEY PAN,F,CENTRAL,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
PATRICIA DOLORES VICTORIA S RODRIGUEZ,F,CENTRAL,,,Track 3 : Personal Management,Track 4 : How to reach out effectively to Gen Zs,,
JAN KREINDEL V LOZANO,M,CENTRAL,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
REGINE V. GERVACIO,F,DAGUPAN,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
JOSE MARIE GARIN ESPANOL,M,DAGUPAN,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
REGINE A. UNGSON,F,DAGUPAN,,,Track 4 : How to make our branches attractive to younger generation,Track 2 : Bible Study,,
CHRISTINA S. BEDAÑA,F,GREENHILLS,,,Track 4 : How to make our branches attractive to younger generation,Track 2 : Bible Study,,
ANDREA G. SARONG,F,GREENHILLS,,,Track 1 : How to run a ministry,Track 2 : Bible Study,,
ANDREA DES D. TRIA,F,GREENHILLS,,,Track 1 : How to run a ministry,Track 3 : Rekindling Commitment,,
MARIE JONEL CHRISTINE E. REYES,F,GREENHILLS,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
SZABELLA ELISSE M. DE CASA,F,GREENHILLS,,,Track 4 : How to make our branches attractive to younger generation,Track 4 : How to reach out effectively to Gen Zs,,
MARY ABIGAIL T OTILANO,F,GREENHILLS,,,Track 1 : How to run a ministry,Track 2 : Bible Study,,
ANNA JOY T. QUIRANTE,F,GREENHILLS,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
DIANNE NICOLE A. PADILLA,F,GREENHILLS,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
TRIXIA SAM O. BURAGA,F,GREENHILLS,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
RENZCIV C. QUICIO,M,GREENHILLS,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
ANGELICA B. SALAZAR,F,GREENHILLS,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
JULIA LEONORE D PEREA,F,GREENHILLS,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
VENNICK JAMES B. PARAS,M,GREENHILLS,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
PAULINE MAE R ROQUID,F,GREENHILLS,,,Track 2 : Participating in worship,Track 4 : How to reach out effectively to Gen Zs,,
ELORDE G GALICIA,M,GREENHILLS,,,Track 3 : Personal Management,Track 1 : Leading worship,,
VICTOR EMMANUEL F. FUENTES,M,GREENHILLS,,,Track 2 : Participating in worship,Track 3 : Rekindling Commitment,,
DEAN R. JULIAN,M,GREENHILLS,,,Track 2 : Participating in worship,Track 1 : Leading worship,,
MATTHEW JOSEPH OBRA PADERON,M,GREENHILLS,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
NERICK JOHN A BAYRON,M,GREENHILLS,,,Track 2 : Participating in worship,Track 4 : How to reach out effectively to Gen Zs,,
JOHN MICHAEL M. DUDAS,M,GREENHILLS,,,Track 3 : Personal Management,Track 2 : Bible Study,,
MARY JANE P VASQUEZ,F,LOS BAÑOS,,,Track 1 : How to run a ministry,Track 3 : Rekindling Commitment,,
CHRISTINE G. BALMES,F,LOS BAÑOS,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
JOHN MARK AZURIN ENCINARES,M,LOS BAÑOS,,,Track 3 : Personal Management,Track 4 : How to reach out effectively to Gen Zs,,
ARIANNE L. AFABLE,F,LOS BAÑOS,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
CHRISTOPHER L. RELATIVO,M,LOS BAÑOS,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
NOEL E. TEMARIO,M,LOS BAÑOS,,,Track 2 : Participating in worship,Track 1 : Leading worship,,
MEANNE P. ANDES,F,LOS BAÑOS,,,Track 4 : How to make our branches attractive to younger generation,Track 3 : Rekindling Commitment,,
KENA D. CARBONERA,F,LOS BAÑOS,,,Track 3 : Personal Management,Track 2 : Bible Study,,
CHARLES EDGAR FRIEDRICK V. BELOSO,M,LUCENA,,,Track 1 : How to run a ministry,Track 2 : Bible Study,,
YSABEL PATRICIA M. ZABELLA,F,LUCENA,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
ABRAM CAESAR C. MAAÑO,M,LUCENA,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
MARK JOVEN VILLACARLOS,M,LUCENA,,,Track 3 : Personal Management,Track 4 : How to reach out effectively to Gen Zs,,
GIFT FLORENCE NEIL A. JASUL,M,LUCENA,,,Track 2 : Participating in worship,Track 3 : Rekindling Commitment,,
LORENZO MARWIN M. LUNA,M,MAKATI,,,Track 1 : How to run a ministry,Track 2 : Bible Study,,
HANS CHRISTIAN ANDERSON A. LABIRAN,M,MAKATI,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
JANA MARIE R. REYNALDO,F,MAKATI,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
GAIL BEATRICE H. VILLAMIEL,F,MAKATI,,,Track 3 : Personal Management,Track 4 : How to reach out effectively to Gen Zs,,
JANINE S. VALERIO,F,MAKATI,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
RUBY ROSA V. MANICANI,F,MAKATI,,,Track 1 : How to run a ministry,Track 3 : Rekindling Commitment,,
NIÑA JEAN S. COMANDA,F,MAKATI,,,Track 2 : Participating in worship,Track 3 : Rekindling Commitment,,
MAYLINDA COMAHIG,F,MAKATI,,,Track 3 : Personal Management,Track 2 : Bible Study,,
JOSE GAMALIEL S FELONGCO,M,MAKATI,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
KRISTINE JOY CUNANAN,F,MAKATI,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
LOI ANN DC SALAS,F,MAKATI,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
NOIMEE NAVARRO,F,MAKATI,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
CYRAH MARIAH CONTRERAS,F,MAKATI,,,Track 2 : Participating in worship,Track 4 : How to reach out effectively to Gen Zs,,
KATRINA MAE J PERNATO,F,MAKATI,,,Track 1 : How to run a ministry,Track 2 : Bible Study,,
JOHN MICHAEL C SERRANO,M,MAKATI,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
DAVID M. SALIM,M,MAKATI,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
ZAIRAH P. AYONAYON,F,MAKATI,,,Track 2 : Participating in worship,Track 1 : Leading worship,,
ZACH DOMINIC D. JACOB,M,MANILA,,,Track 1 : How to run a ministry,Track 2 : Bible Study,,
MERSAN S. CANONIGO JR.,M,MANILA,,,Track 1 : How to run a ministry,Track 3 : Rekindling Commitment,,
DOMINIQUE T. CRUZ,F,MANILA,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
NEIL RYAN NUNEZ,M,MANILA,,,Track 1 : How to run a ministry,Track 2 : Bible Study,,
MARY BERNADINE C. CALICDAN,F,MANILA,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
MA. ELENA G. DUMAUAL,F,MANILA,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
DIMPOL CANTOR REGUINDIN,F,MANILA,,,Track 2 : Participating in worship,Track 1 : Leading worship,,
KARREN N. BUENAOBRA,F,MANILA,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
BEVERLY GRACE C. ALCAYNO,F,MANILA,,,Track 2 : Participating in worship,Track 4 : How to reach out effectively to Gen Zs,,
SHIELA MAE B NIONES,F,MANILA,,,Track 2 : Participating in worship,Track 4 : How to reach out effectively to Gen Zs,,
LIEZL S. MANZANO,F,MANILA,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
MARIANE G. ALMENDRAL,F,MANILA,,,Track 4 : How to make our branches attractive to younger generation,Track 3 : Rekindling Commitment,,
JAYSON C. FRANCO,M,MANILA,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
JARIZA DARYL T. MEJIA,F,MANILA,,,Track 3 : Personal Management,Track 2 : Bible Study,,
JUDERICO TANAY,M,MANILA,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
JOSH FELJON A. AJOC,M,MANILA,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
NADINE ROYCE T. NUÑEZ,F,MANILA,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
MICHELLE G. CATUBIG,F,MANILA,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
MARK ANTHONY C. PASCUAL,M,MANILA,,,Track 3 : Personal Management,Track 1 : Leading worship,,
RAYMOND P. DALAY,M,OTHERS,,,,,,
J-ZEL A. MAGTIBAY,F,OTHERS,,,,,,
ZIZETTE NUQUI DALAY,F,OTHERS,,,,,,
ENRICO A. OCAMPO,M,OTHERS,,,,,,
PETER JESS V. LEGASPI,M,OTHERS,,,,,,
MA CHRISTIANA CARMELA DALANGIN,F,OTHERS,,,,,,
TED TE,M,OTHERS,,,,,,
KRISTEL MAE OLIVEROS,F,OTHERS,,,,,,
JEROME J. ORBE,M,OTHERS,,,,,,
PATRICK ANTHONY M. CALALO,M,OTHERS,,,,,,
ELMER S. LACSAMANA,M,OTHERS,,,,,,
AURORA V LACASTE,F,OTHERS,,,,,,
THERESE GABRIELLE A. SOLA,F,QUEZON CITY,,,Track 4 : How to make our branches attractive to younger generation,Track 4 : How to reach out effectively to Gen Zs,,
ANDREA COLEEN P. VELASCO,F,QUEZON CITY,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
ANGELINE CAMILLE C. JIMENEZ,F,QUEZON CITY,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
JEREMIAH A. SALVEDIA,M,QUEZON CITY,,,Track 4 : How to make our branches attractive to younger generation,Track 4 : How to reach out effectively to Gen Zs,,
HANNAH LUZ R. IGNACIO,F,QUEZON CITY,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
ROBIN VICTORIA N. RACELA,F,QUEZON CITY,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
MA ANGELICA NICOLE R JACOBA,F,QUEZON CITY,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
HONEY CRISRIL M. CALIMOT,F,QUEZON CITY,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
MARIA ANGELICA P. AGBAYANI,F,QUEZON CITY,,,Track 2 : Participating in worship,Track 3 : Rekindling Commitment,,
MICHELLE CARLA M. CABUCO,F,QUEZON CITY,,,Track 4 : How to make our branches attractive to younger generation,Track 3 : Rekindling Commitment,,
TATYANA MARIE U. GONZAGA,F,QUEZON CITY,,,Track 3 : Personal Management,Track 4 : How to reach out effectively to Gen Zs,,
DANIEL GABRIEL R. DE GUZMAN,M,QUEZON CITY,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
MARIA SONJA B. DELA CRUZ,F,QUEZON CITY,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
DAVID MIGUEL R. DE GUZMAN,M,QUEZON CITY,,,Track 4 : How to make our branches attractive to younger generation,Track 2 : Bible Study,,
JOSE ROSENDO R. CACHO ,M,QUEZON CITY,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
WALFREDO L. GARCIA II,M,QUEZON CITY,,,Track 3 : Personal Management,Track 1 : Leading worship,,
LANCE MATTHEW MIRANDA CALMA,M,QUEZON CITY,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
THERESE PAMAN,F,YP LNP,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
EZEKIELA ARCEO LACSAMANA,F,YP PAMPANGA - BALE,,,Track 1 : How to run a ministry,Track 2 : Bible Study,,
CHRISTINE ALEXANDRA S. ALMAZAN,F,YP PAMPANGA - BALE,,,Track 2 : Participating in worship,Track 1 : Leading worship,,` ;
