const CSV_DATA =
`Name,Gender,Branch,Room Number,Car Number,D1T,D2T,Outing Number,Separate Event Number
JOVINIA S LUCAS,F,BAGUIO,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
JARA L. ADOLFO,F,BAGUIO,,,,,,
EZEKIELA ARCEO LACSAMANA,F,YP PAMPANGA - BALE,,,Track 1 : How to run a ministry,Track 2 : Bible Study,,
AIRAM MIGUEL M. DIZON,M,ANGELES,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
ALLAINE CASTRO GALANG,F,ANGELES,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
AYN CYRIL TIANGCO,M,CAVITE,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
JEREMIAH A. SALVEDIA,M,QUEZON CITY,,,,,,
MARIE JONEL CHRISTINE E. REYES,F,GREENHILLS,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
HANNAH LUZ R. IGNACIO,F,QUEZON CITY,,,,,,
ROBIN VICTORIA N. RACELA,F,QUEZON CITY,,,,,,
SZABELLA ELISSE M. DE CASA,F,GREENHILLS,,,Track 4 : How to make our branches attractive to younger generation,Track 4 : How to reach out effectively to Gen Zs,,
THERESE GABRIELLE A. SOLA,F,QUEZON CITY,,,,,,
MARY ABIGAIL T OTILANO,F,GREENHILLS,,,Track 1 : How to run a ministry,Track 2 : Bible Study,,
ANNA JOY T. QUIRANTE,F,GREENHILLS,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
DIANNE NICOLE A. PADILLA,F,GREENHILLS,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
MARK ANGEL V. REYES,M,CAVITE,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
ELLISON DALE M. RAGUDO,M,BAGUIO,,,,,,
FRANCISCO EZEKIEL M. ESPINOSA,M,CAVITE,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
KIM PAULO SIERRA,M,CAVITE,,,Track 4 : How to make our branches attractive to younger generation,Track 2 : Bible Study,,
VEENUZ MARGARETTE C. DEL ROSARIO,F,CAVITE,,,Track 1 : How to run a ministry,Track 2 : Bible Study,,
KATERINE GAIL CATACUTAN PANGILINAN,F,CAVITE,,,Track 1 : How to run a ministry,Track 3 : Rekindling Commitment,,
CATHERINE ROSE D. SACANLE,F,BAGUIO,,,Track 1 : How to run a ministry,Track 3 : Rekindling Commitment,,
IVY MELISSA M. BALUYOT,F,BGC,,,,,,
SAMANTHA B. MARWELES,F,BGC,,,,,,
ARNEL BIEN H. FRANCISCO,M,BGC,,,,,,
RINO C. BALUYOT JR.,M,BGC,,,,,,
ARIANNE NINA M. AREVALO,F,BGC,,,,,,
RINA MARIE A. VERANO,F,CAVITE,,,Track 4 : How to make our branches attractive to younger generation,Track 3 : Rekindling Commitment,,
TRIXIA SAM O. BURAGA,F,GREENHILLS,,,Track 3 : Personal Management,Track 2 : Bible Study,,
RENZCIV C. QUICIO,M,GREENHILLS,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
ROWELL IAN S. SALVADOR,M,CAVITE,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
SEAN VINCENT L. CABEZAS,M,CAVITE,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
CHRISTINA S. BEDAÑA,F,GREENHILLS,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
ANGELICA B. SALAZAR,F,GREENHILLS,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
JULIA LEONORE D PEREA,F,GREENHILLS,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
VENNICK JAMES B. PARAS,M,GREENHILLS,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
ANDREA COLEEN P. VELASCO,F,QUEZON CITY,,,,,,
PAULINE MAE R ROQUID,F,GREENHILLS,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
ELORDE G GALICIA,M,GREENHILLS,,,Track 3 : Personal Management,Track 1 : Leading worship,,
ANDREA G. SARONG,F,GREENHILLS,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
MICHELLE ANGELICA C. ARRANZ,F,BGC,,,,,,
JIANE RHANE A. REGALA,F,ANGELES,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
ALDRINNE M. ARRO,M,ALABANG,,,Track 3 : Personal Management,Track 2 : Bible Study,,
KIMBERLY Q. DELA CRUZ,F,ANGELES,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
VICTOR EMMANUEL F. FUENTES,M,GREENHILLS,,,Track 1 : How to run a ministry,Track 3 : Rekindling Commitment,,
AILEEN MAY B. TOLENTINO,F,CAVITE,,,Track 2 : Participating in worship,Track 4 : How to reach out effectively to Gen Zs,,
RAYMOND P. DALAY,M,OTHERS,,,,,,
J-ZEL A. MAGTIBAY,F,OTHERS,,,,,,
ZIZETTE NUQUI DALAY,F,YP PAMPANGA - BALE,,,,,,
RHOMEL IGNATIUS B. MARCOJOS,M,CENTRAL,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
THERESE PAMAN,F,YP LNP,,,,,,
MA ANGELICA NICOLE R JACOBA,F,QUEZON CITY,,,,,,
HONEY CRISRIL M. CALIMOT,F,QUEZON CITY,,,,,,
MARIA ANGELICA P. AGBAYANI,F,QUEZON CITY,,,,,,
ANDREA DES D. TRIA,F,GREENHILLS,,,Track 2 : Participating in worship,Track 3 : Rekindling Commitment,,
ROLLAINE JOVEL JAMLIG PADDRES,F,CAVITE,,,Track 4 : How to make our branches attractive to younger generation,Track 4 : How to reach out effectively to Gen Zs,,
MICHELLE CARLA M. CABUCO,F,QUEZON CITY,,,,,,
RHOMEL ISAAC B. MARCOJOS,M,BGC,,,,,,
PRECILYN B. CASPILLO,F,BGC,,,,,,
PRINCESS ANN L. PAGBILAO,F,CAVITE,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
ALAIZA T. ENCARNACION,F,CAVITE,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
CHRISTINE JOY M. ROMILLA,F,CAVITE,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
ENRICO A. OCAMPO,M,YP PAMPANGA - BALE,,,,,,
MICHAELA ANTONETTE M. PANTIG,F,ANGELES,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
ANGELO V. DEGORIO,M,ALABANG,,,Track 2 : Participating in worship,Track 1 : Leading worship,,
NIKI G. INARDA,F,ANGELES,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
JOSE LORENZO M. CUNANAN,M,ANGELES,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
HANS CHRISTIAN ANDERSON A. LABIRAN,M,MAKATI,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
KATHY ROSE T. SANTOS,F,ANGELES,,,Track 1 : How to run a ministry,Track 2 : Bible Study,,
REMEDIOS BEATRICE N. GAON,F,CAVITE,,,Track 1 : How to run a ministry,Track 2 : Bible Study,,
LEMUEL GAVIN SARET,M,ALABANG,,,Track 1 : How to run a ministry,Track 2 : Bible Study,,
JON RAY BIEN D. LOGICA,M,ALABANG,,,Track 4 : How to make our branches attractive to younger generation,Track 2 : Bible Study,,
JAN MARVIN P. DELA CRUZ,M,ANGELES,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
KIMBERLY F. POLICARPIO,F,ANGELES,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
JILLIAN MAE D. GUIAO,F,ANGELES,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
JOHN ADRIAN A. CIELOS,M,ALABANG,,,Track 4 : How to make our branches attractive to younger generation,Track 2 : Bible Study,,
JELLY B AGUSTIN,F,ANGELES,,,Track 2 : Participating in worship,Track 4 : How to reach out effectively to Gen Zs,,
PAMELA ANN M. DUQUE,F,ALABANG,,,Track 3 : Personal Management,Track 2 : Bible Study,,
DEO J. JOLLOSO,M,CAVITE,,,Track 2 : Participating in worship,Track 4 : How to reach out effectively to Gen Zs,,
RICHMOND M. BANZUELO,M,ALABANG,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
IÑIGO MIGUEL G VILLANUEVA,M,ALABANG,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
ANJIL S. AUSTRIA,M,ALABANG,,,Track 3 : Personal Management,Track 4 : How to reach out effectively to Gen Zs,,
JANA MARIE R. REYNALDO,F,MAKATI,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
CHRISTIAN VANESSA OLEA AUSTRIA,F,ALABANG,,,Track 3 : Personal Management,Track 2 : Bible Study,,
OLEEN JOYCE B FLORENDO,F,ALABANG,,,Track 2 : Participating in worship,Track 3 : Rekindling Commitment,,
ANGELINE CAMILLE C. JIMENEZ,F,QUEZON CITY,,,,,,
TATYANA MARIE U. GONZAGA,F,QUEZON CITY,,,,,,
JOBELLE S. GALLO,F,ALABANG,,,Track 4 : How to make our branches attractive to younger generation,Track 4 : How to reach out effectively to Gen Zs,,
GAIL BEATRICE H. VILLAMIEL,F,MAKATI,,,Track 3 : Personal Management,Track 4 : How to reach out effectively to Gen Zs,,
GELLAINE A. SALVACION,F,BATANGAS,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
ERICA MAE I. MERCADO,F,BATANGAS,,,Track 4 : How to make our branches attractive to younger generation,Track 4 : How to reach out effectively to Gen Zs,,
CHRISHA MAE S. REMORERAS,F,BATANGAS,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
DENISE JAMES C CHUA,F,BATANGAS,,,Track 4 : How to make our branches attractive to younger generation,Track 3 : Rekindling Commitment,,
RIZA L. BERSABAL,F,ALABANG,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
JANINE S. VALERIO,F,MAKATI,,,Track 1 : How to run a ministry,Track 2 : Bible Study,,
RUBY ROSA V. MANICANI,F,MAKATI,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
NIÑA JEAN S. COMANDA,F,MAKATI,,,Track 4 : How to make our branches attractive to younger generation,Track 3 : Rekindling Commitment,,
JAKE D. DELA CRUZ,M,ALABANG,,,Track 4 : How to make our branches attractive to younger generation,Track 4 : How to reach out effectively to Gen Zs,,
MIKHAELLA L RACELIS,F,ALABANG,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
MAYLINDA COMAHIG,F,MAKATI,,,Track 3 : Personal Management,Track 2 : Bible Study,,
DANIEL GABRIEL R. DE GUZMAN,M,QUEZON CITY,,,,,,
KRISTALYNNE B. GREGANDA,F,CABUYAO,,,,,,
MARIA SONJA B. DELA CRUZ,F,QUEZON CITY,,,,,,
IRA JAMAICA T. LACO,F,ALABANG,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
IRINE T. SALES,F,BGC,,,,,,
JUDY ANNE J PEÑA,F,BATANGAS,,,Track 1 : How to run a ministry,Track 2 : Bible Study,,
JOHN MARK AZURIN ENCINARES,M,LOS BAÑOS,,,,,,
ARIANNE L. AFABLE,F,LOS BAÑOS,,,,,,
ISMINE JOICE S. HIPOLITO,F,ANGELES,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
CHRISTOPHER L. RELATIVO,M,LOS BAÑOS,,,,,,
MARK SPENCER R. MALIG,M,ANGELES,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
AMIEL M. MALONZO,M,ANGELES,,,,,,
CHARISSE N. SANCHEZ,F,CENTRAL,,,Track 1 : How to run a ministry,Track 3 : Rekindling Commitment,,
CARLOS V. PALATTAO,M,CENTRAL,,,Track 4 : How to make our branches attractive to younger generation,Track 3 : Rekindling Commitment,,
JAN AUDI BLEZ M. NAVARRO,M,ALABANG,,,Track 2 : Participating in worship,Track 1 : Leading worship,,
JUN EXEQUIEL E. SAYLON,M,ANGELES,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
SHAINA R DUCUT,F,CENTRAL,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
REGINE V. GERVACIO,F,DAGUPAN,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
JOSE MARIE GARIN ESPANOL,M,DAGUPAN,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
MARC RAZEL B. BUENAFE,M,ALABANG,,,Track 1 : How to run a ministry,Track 3 : Rekindling Commitment,,
MARY ANTONETTE B. MIRANDA,F,BATANGAS,,,Track 3 : Personal Management,Track 4 : How to reach out effectively to Gen Zs,,
MARY LOURDES D. BORBON,F,BATANGAS,,,Track 1 : How to run a ministry,Track 2 : Bible Study,,
DYVE D CANDAZA,M,ALABANG,,,Track 3 : Personal Management,Track 4 : How to reach out effectively to Gen Zs,,
MARK JASON UMAS-AS CASIL,M,CAVITE,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
ALDWYN JOHN T BAUTISTA,M,ANGELES,,,Track 3 : Personal Management,Track 1 : Leading worship,,
MANLEY M. SALAZAR JR.,M,CENTRAL,,,Track 3 : Personal Management,Track 1 : Leading worship,,
KRISHIA JANINE P. GUBATON,F,ANGELES,,,Track 4 : How to make our branches attractive to younger generation,Track 2 : Bible Study,,
CHRISTIAN M DELA GRACIA,M,CAVITE,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
REGINE A. UNGSON,F,DAGUPAN,,,Track 4 : How to make our branches attractive to younger generation,Track 2 : Bible Study,,
MERIE JUDAINE D. CARINGAL,F,BGC,,,,,,
KATHERINE MENDEZ,F,BATANGAS,,,Track 1 : How to run a ministry,Track 3 : Rekindling Commitment,,
"PANGILINAN, GLENINE ANNE P",F,ANGELES,,,Track 3 : Personal Management,Track 1 : Leading worship,,
RICHARD DEAN F. BASA,M,BAGUIO,,,,,,
DOMINIQUE T. CRUZ,F,MANILA,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
ANGEL S. DEL ROSARIO,M,BATANGAS,,,Track 3 : Personal Management,Track 4 : How to reach out effectively to Gen Zs,,
LORENZO MARWIN M. LUNA,M,MAKATI,,,,,,
JOSHUA MIKHAEL O. BONDOC,M,CENTRAL,,,Track 3 : Personal Management,Track 1 : Leading worship,,
JAMINO F. GONZALES,M,CENTRAL,,,Track 3 : Personal Management,Track 4 : How to reach out effectively to Gen Zs,,
"JONINA RAE, DARLUCIO, VILVESTRE",F,CENTRAL,,,Track 4 : How to make our branches attractive to younger generation,Track 4 : How to reach out effectively to Gen Zs,,
ARLENE WARKEY PAN,F,CENTRAL,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
JOSE GAMALIEL S FELONGCO,M,MAKATI,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
PATRICIA DOLORES VICTORIA S RODRIGUEZ,F,CENTRAL,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
NEIL RYAN NUNEZ,M,MANILA,,,Track 1 : How to run a ministry,Track 2 : Bible Study,,
JUVY GRACE B. ADRIAS,F,CAVITE,,,Track 1 : How to run a ministry,Track 3 : Rekindling Commitment,,
LYZETTE A. LAZARTE,F,BATANGAS,,,Track 3 : Personal Management,Track 2 : Bible Study,,
MARY BERNADINE C. CALICDAN,F,MANILA,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
MA. ELENA G. DUMAUAL,F,MANILA,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
DIMPOL CANTOR REGUINDIN,F,MANILA,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
KARREN N. BUENAOBRA,F,MANILA,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
KRISTINE JOY CUNANAN,F,MAKATI,,,Track 2 : Participating in worship,Track 1 : Leading worship,,
BEVERLY GRACE C. ALCAYNO,F,MANILA,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
FRANCES MARGARET D CHUAHIONG,F,CAVITE,,,Track 3 : Personal Management,Track 2 : Bible Study,,
LOI ANN DC SALAS,F,MAKATI,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
DAVID MIGUEL R. DE GUZMAN,M,QUEZON CITY,,,,,,
MARY CARELL D. SABA,F,CAVITE,,,Track 1 : How to run a ministry,Track 3 : Rekindling Commitment,,
JAN KREINDEL V LOZANO,M,CENTRAL,,,Track 3 : Personal Management,Track 1 : Leading worship,,
JAYCEL C. CAPUNONG,F,CAVITE,,,Track 3 : Personal Management,Track 1 : Leading worship,,
MARY JANE P VASQUEZ,F,LOS BAÑOS,,,,,,
NOEL E. TEMARIO,M,LOS BAÑOS,,,,,,
MEANNE P. ANDES,F,LOS BAÑOS,,,,,,
NICOLE JOYCE V TUPAS,F,CABUYAO,,,,,,
NOIMEE NAVARRO,F,MAKATI,,,Track 3 : Personal Management,Track 4 : How to reach out effectively to Gen Zs,,
JOANNA MARIE I QUINTOS,F,ALABANG,,,Track 3 : Personal Management,Track 4 : How to reach out effectively to Gen Zs,,
CHRISTINE G. BALMES,F,LOS BAÑOS,,,Track 3 : Personal Management,Track 4 : How to reach out effectively to Gen Zs,,
JON SAMUEL S MENDEZ,M,ALABANG,,,Track 4 : How to make our branches attractive to younger generation,Track 3 : Rekindling Commitment,,
IÑIGO MIGUEL G. VILLANUEVA,M,ALABANG,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
JUAN FRANCO B DE GUZMAN,M,CABUYAO,,,,,,
MARK DAVID T. DOMINO,M,CABUYAO,,,,,,
SHIELA MAE B NIONES,F,MANILA,,,Track 3 : Personal Management,Track 4 : How to reach out effectively to Gen Zs,,
LIEZL S. MANZANO,F,MANILA,,,Track 1 : How to run a ministry,Track 1 : Leading worship,,
MARIANE G. ALMENDRAL,F,MANILA,,,Track 1 : How to run a ministry,Track 3 : Rekindling Commitment,,
JAYSON C. FRANCO,M,MANILA,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
JARIZA DARYL T. MEJIA,F,MANILA,,,Track 3 : Personal Management,Track 2 : Bible Study,,
DEAN R. JULIAN,M,GREENHILLS,,,Track 2 : Participating in worship,Track 1 : Leading worship,,
MATTHEW JOSEPH OBRA PADERON,M,GREENHILLS,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
MAUI ARCA,M,ALABANG,,,Track 2 : Participating in worship,Track 1 : Leading worship,,
CAMILLE R. GARCIA,F,ALABANG,,,Track 2 : Participating in worship,Track 3 : Rekindling Commitment,,
MARVIN SANTOS MACAPINLAC,M,ANGELES,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
KENA D. CARBONERA,F,LOS BAÑOS,,,,,,
CYRAH MARIAH CONTRERAS,F,MAKATI,,,Track 2 : Participating in worship,Track 4 : How to reach out effectively to Gen Zs,,
JUDERICO TANAY,M,MANILA,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
JOSE ROSENDO R. CACHO ,M,QUEZON CITY,,,,,,
KATRINA MAE J PERNATO,F,MAKATI,,,Track 1 : How to run a ministry,Track 2 : Bible Study,,
JOSH FELJON A. AJOC,M,MANILA,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
HENSON B. GLODO,M,CENTRAL,,,Track 3 : Personal Management,Track 1 : Leading worship,,
JOHN MICHAEL C SERRANO,M,MAKATI,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
DAVID M. SALIM,M,MAKATI,,,Track 1 : How to run a ministry,Track 4 : How to reach out effectively to Gen Zs,,
PETER JESS V. LEGASPI,M,OTHERS,,,,,,
MA CHRISTIANA CARMELA DALANGIN,F,YP LNP,,,,,,
TED TE,M,OTHERS,,,,,,
KRISTEL MAE OLIVEROS,F,OTHERS,,,,,,
JAIME JUROE S BONITO,M,ANGELES,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
NERICK JOHN A BAYRON,M,GREENHILLS,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
JOHN MICHAEL M. DUDAS,M,GREENHILLS,,,Track 3 : Personal Management,Track 2 : Bible Study,,
WALFREDO L. GARCIA II,M,QUEZON CITY,,,Track 3 : Personal Management,Track 1 : Leading worship,,
LANCE MATTHEW MIRANDA CALMA,M,QUEZON CITY,,,,,,
RICHARD M. BUHAYO,M,BAGUIO,,,,,,
NADINE ROYCE T. NUÑEZ,F,MANILA,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
JEROME J. ORBE,M,OTHERS,,,,,,
PATRICK ANTHONY M. CALALO,M,OTHERS,,,,,,
MICHELLE G. CATUBIG,F,MANILA,,,Track 4 : How to make our branches attractive to younger generation,Track 3 : Rekindling Commitment,,
ZACH DOMINIC D. JACOB,M,MANILA,,,Track 3 : Personal Management,Track 2 : Bible Study,,
ELMER S. LACSAMANA,M,OTHERS,,,,,,
MARK ANTHONY C. PASCUAL,M,MANILA,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
MERSAN S. CANONIGO JR.,M,MANILA,,,Track 3 : Personal Management,Track 3 : Rekindling Commitment,,
ZAIRAH P. AYONAYON,F,MAKATI,,,Track 4 : How to make our branches attractive to younger generation,Track 1 : Leading worship,,
JAIME JUROE S BONITO,M,ANGELES,,,,,,
NERICK JOHN A BAYRON,M,GREENHILLS,,,Track 2 : Participating in worship,Track 2 : Bible Study,,
JOHN MICHAEL M. DUDAS,M,GREENHILLS,,,,,,` ;
